[package]
name = "md_linker"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
# Add dev-only dependencies here if needed in the future

[lib]
path = "src/lib.rs"

[[bin]]
name = "md_linker"
path = "src/main.rs"

[workspace]
